# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-07 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221207_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='BankStatement',
            new_name='Bank_Statement',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ProofofAddress',
            new_name='Proof_of_Address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ProofofID',
            new_name='Proof_of_ID',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Workpayslip',
            new_name='Work_payslip',
        ),
    ]
