# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221207_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Bank_Statement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Contract',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Proof_of_Address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Proof_of_ID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Work_payslip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
