# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-08 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221208_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='file',
            new_name='Documents',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='title',
            new_name='Your_Name',
        ),
    ]
