# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-08 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221208_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='User_Documents',
        ),
    ]
