# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-08 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221208_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Documents',
            new_name='User_Document',
        ),
    ]
