# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20221208_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='city',
            field=models.ForeignKey(default='name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='property.City'),
        ),
        migrations.AlterField(
            model_name='images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(blank=True, default=1, max_length=300, on_delete=django.db.models.deletion.DO_NOTHING, to='property.City'),
        ),
        migrations.AlterField(
            model_name='neighborhoodimage',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='property.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default='', max_length=300, on_delete=django.db.models.deletion.DO_NOTHING, to='property.Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtor.Realtor'),
        ),
    ]
