# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-11 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20221211_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighborhoodimage',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='NeighborhoodImage',
        ),
    ]
